name: Update Nepali Date

on:
  schedule:
    - cron: '0 */2 * * *' # Every 2 hours

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate updated date.json
        run: npm run generate

      - name: Commit and push
        run: |
          git config --global user.name "Nepali Date API"
          git config --global user.email "actions@github.com"
          git add date.json
          git commit -m "ğŸ—“ï¸ Update Nepali date [skip ci]" || echo "No changes"
          git push
