name: Update Nepali Date & Uptime

on:
  schedule:
    - cron: '*/15 * * * *' # every 15 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate updated date.json
        run: npm run generate

      - name: Generate uptime.json
        run: npm run uptime

      - name: Commit and push changes
        run: |
          git config --global user.name "birajrai"
          git config --global user.email "70630924+birajrai@users.noreply.github.com"
          git add date.json uptime.json
          git commit -m "ğŸ—“ï¸ & ğŸ“¡ Update Nepali date and uptime [skip ci]" || echo "No changes"
          git push
